name: ci-test

on:
  push:
    branches: [ kinma-golangBackend ]
  pull_request:
    branches: [ kinma-golangBackend ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: root
          POSTGRES_DB: kinma_db
        #Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    #Install v4.15.1 to align with local test
    - name: Install migrate
      run: |
      curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz
      sudo mv migrate.linux-amd64 /usr/bin/migrate
      which migrate
    
    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
